# Generated by Django 6.0 on 2026-01-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tipoatendimento_pacote_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
