# Generated by Django 6.0 on 2026-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_solicitacaoagendamento_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_roles',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Profissional')], null=True),
        ),
    ]
