# Generated by Django 5.0.2 on 2024-03-30 20:55

from django.db import migrations

def populate_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    UserRole = apps.get_model('users', 'UserRole')

    # Create roles
    admin_role, _ = UserRole.objects.get_or_create(nome_cargo='Admin', defaults={'ativo': True})
    profissional_role, _ = UserRole.objects.get_or_create(nome_cargo='Profissional', defaults={'ativo': True})

    # Update users
    for user in User.objects.all():
        if user.role == 'ADMIN':
            user.users_roles = admin_role
        elif user.role == 'PROFISSIONAL':
            user.users_roles = profissional_role
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userrole_alter_user_users_roles'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
    ]
