# Generated by Django 6.0 on 2026-03-31 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_populate_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, limit_choices_to={'users_roles__nome_cargo': 'Profissional'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'users_roles__nome_cargo': 'Profissional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='profissional_solicitado',
            field=models.ForeignKey(limit_choices_to={'users_roles__nome_cargo': 'Profissional'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
