# Generated by Django 6.0 on 2026-04-01 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_set_default_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='eh_profissional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, limit_choices_to={'users_roles__eh_profissional': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'users_roles__eh_profissional': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='profissional_solicitado',
            field=models.ForeignKey(limit_choices_to={'users_roles__eh_profissional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
