# Generated by Django 6.0 on 2026-04-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_populate_eh_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentual_taxa_reposicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='valor_taxa_reposicao_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
