# Generated by Django 6.0 on 2026-04-02 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_percentual_taxa_reposicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='profissional',
            field=models.ForeignKey(blank=True, limit_choices_to={'users_roles__eh_profissional': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacotes_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
