# Generated by Django 6.0 on 2026-04-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_agendamento_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Ex: 0,2,4 (seg, qua, sex)', max_length=50, null=True),
        ),
    ]
