# Generated by Django 6.0 on 2026-04-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userrole_pode_gerenciar_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='renovado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacao', to='users.pacote'),
        ),
    ]
