# Generated by Django 6.0 on 2026-01-03 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atendimento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_total', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_por_sessao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=50)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='users.paciente')),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='users.tipoatendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('FALTA', 'Falta'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=50)),
                ('valor_repasse_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_repasse', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=50)),
                ('profissional', models.ForeignKey(limit_choices_to={'role': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='users.pacote')),
            ],
        ),
    ]
