# Generated by Django 6.0 on 2026-01-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paciente_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFISSIONAL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('FALTA', 'Falta'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=50),
        ),
    ]
