# Generated by Django 6.0 on 2026-01-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_agendamento_data_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFISSIONAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
