# Generated by Django 6.0 on 2026-01-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_solicitacaoagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoagendamento',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
