# Generated by Django 6.0 on 2026-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_role_alter_agendamento_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='pode_gerenciar_agendamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='pode_gerenciar_pacientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='pode_gerenciar_pacotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='pode_gerenciar_tipos_atendimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='pode_gerenciar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='visualizar_tudo',
            field=models.BooleanField(default=False),
        ),
    ]
