# Generated by Django 6.0 on 2026-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pacote_data_inicio_pacote_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='pode_gerenciar_financeiro',
            field=models.BooleanField(default=False),
        ),
    ]
