# Generated by Django 6.0 on 2026-04-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_pacote_renovado_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
