# Generated by Django 6.0 on 2026-04-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_pacote_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatendimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
