# Generated by Django 6.0 on 2026-04-12 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_paciente_bairro_paciente_cep_paciente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='users.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
