# Generated by Django 6.0 on 2026-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_enable_unaccent'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='pacote',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('PIX', 'PIX'), ('ESPECIE', 'Espécie'), ('OUTROS', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('FALTA', 'Falta'), ('REMARCADO', 'Remarcado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=50),
        ),
    ]
