# Generated by Django 6.0 on 2026-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_forma_pagamento_to_pacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoatendimento',
            name='cor',
            field=models.CharField(default='#406657', max_length=7),
        ),
    ]
